### PR TITLE
Add option to set the maximum number of connections

### PR DESCRIPTION
**Pull request by greschd**
Added a keyword argument ``max_connections`` to set the maximum number of connections. The default value (5) corresponds to the previous behavior.

### CODE REVIEW

**Comment by jamesnunn** [comment]
I'm ok with the change but a couple more things I think, please:

- the `__repr__` method should have the `max_connections` represented
- at least a naive check on the value of `max_connections` being an `int` (e.g. `assert isinstance(max_connections, int)`) - I could imagine passing a `'5'` might give us a confusing error message from subprocess
- _maybe_ adding a test to `TestPGTestWithParameters` (I can't think off the top of my head what you'd use to check that which is why it's a maybe)

**Comment by jamesnunn** [comment]
Also I've updated the travis config to handle the old postgres installation which exists by default so the build itself shouldn't error. I haven't considered testing compatibility with multiple versions of postgres so if you know of any snags for old/current versions please let me know.

**Comment by greschd** [comment]
Ok, I've added the ``__repr__`` and an assertion for ``isinstance(max_connections, numbers.Integral)``. For the tests, I've used ``psycopg2`` to execute ``SHOW max_connections;``. I'm not sure if that's ok, or if you would like the tests to not use the third party drivers.
The tests run on the Linux machines now, but it seems the OSX builds are still broken.

**Comment by jamesnunn** [comment]
`psycopg2` is fine as it's already a dependency declared in the `tox` config. I'm ok with the build failing for osx for this as it looks like a problem specific to travis. That can be sorted another time. Thanks.

**Comment by greschd** [comment]
Thanks for accepting!

**Pull request merged**
