### PR TITLE
fix issues on ubuntu 18.04

### LINKED ISSUE #8: pgtest fails on ubuntu 18.04
Pgtest fails on ubuntu 18.04, as it cannot find the pg_ctl:

```
In [1]: from pgtest.pgtest import PGTest

In [2]: import psycopg2

In [3]: pg = PGTest()
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-3-037313004511> in <module>()
----> 1 pg = PGTest()

/home/epfl/work/venv-lsmo/local/lib/python2.7/site-packages/pgtest/pgtest.py in __init__(self, username, port, log_file, no_cleanup, copy_cluster, base_dir, pg_ctl, max_connections)
    308 
    309         self._create_dirs()
--> 310         self._init_base_dir()
    311         self._set_dir_permissions()
    312         self._start_server()

/home/epfl/work/venv-lsmo/local/lib/python2.7/site-packages/pgtest/pgtest.py in _init_base_dir(self)
    461                 _, err = proc.communicate()
    462                 if err:
--> 463                     raise IOError(err)
    464             assert is_valid_cluster_dir(self._cluster), (
    465                 'Failed to create cluster: {path}').format(path=self._cluster)

IOError: /bin/sh: 1: None: not found
```

### LINKED ISSUE #9: PGTest() fails with PostgreSQL 10 on Ubuntu 18.04 due to default `max_wal_senders`
I don't know where this default is coming is coming from, but PostgreSQL 10 on Ubuntu 18.04 has a default `max_wal_senders = 10` and PostgreSQL requires the `max_connections` to be larger than the number of `max_wal_senders` and therefore the default `pgtest.PGTest()` refuses to start the server with the following log in `/tmp/mytemp/pgtest_log.txt`:

```
postgres: max_wal_senders must be less than max_connections
```

So, either set the default for `max_connections` to 11 or pass `--max_wal_senders=...` to the postgres process.

### PR DESCRIPTION
**Pull request by ltalirz**
* set `max_connections=11` (fix #9, fix #8 )
 * fix issue with travis build by switching to their `apt:` addons
 * add search for `pg_ctl` location that removes dependency on `locate` on ubuntu 18.04

### CODE REVIEW

**Comment by ltalirz** [comment]
@jamesnunn Are you still maintaining `pgtest` or would you like help with this?

**Comment by ltalirz** [comment]
resolved conflicts :-)

**Comment by ltalirz** [comment]
Thanks a lot for moving forward with this!
Could I kindly ask for a 1.1.1 release on pypi as well?
(and perhaps a corresponding v1.1.1 tag of the git repository)

**Comment by jamesnunn** [comment]
I just released this on PyPi, 1.2.0 . Thanks for the contribution

**Comment by ltalirz** [comment]
you're welcome, and thanks for the release!

**Pull request merged**
